//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        public string EmployeeCode { get; set; }
        public double CarPaid { get; set; }
        public double Medical_Allowance { get; set; }
        public double Utility_Allowance { get; set; }
        public double Bonus_Propotionate { get; set; }
        public double DisLocation { get; set; }
        public double COLA { get; set; }
        public double Cell_Allowance { get; set; }
        public double EOBI_Company { get; set; }
        public double Hardship { get; set; }
        public double Provident_Fund { get; set; }
        public double SpecialAllowance { get; set; }
        public double Fuel_Amount { get; set; }
        public double Washing_Allowance { get; set; }
        public double Basic_Salary { get; set; }
        public double Maintenance_Allowance { get; set; }
        public double Car_Allowance { get; set; }
        public double HouseRent { get; set; }
    }
}
