//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int LogId { get; set; }
        public string TableName { get; set; }
        public int PrimaryKey { get; set; }
        public string DataXML { get; set; }
        public int OperationTypeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public string DataJson { get; set; }
        public Nullable<int> ParentKey { get; set; }
    
        public virtual Setup_OperationType Setup_OperationType { get; set; }
    }
}
