//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Detail
    {
        public HCM_Setup_Detail()
        {
            this.HCM_ArrearHistory = new HashSet<HCM_ArrearHistory>();
            this.HCM_Atribute_Mapping = new HashSet<HCM_Atribute_Mapping>();
            this.HCM_Company_Settings = new HashSet<HCM_Company_Settings>();
            this.HCM_CompanyFormula = new HashSet<HCM_CompanyFormula>();
            this.HCM_EmployeeAccountDetail = new HashSet<HCM_EmployeeAccountDetail>();
            this.HCM_EmployeeAccountDetail1 = new HashSet<HCM_EmployeeAccountDetail>();
            this.HCM_EmployeeSalary = new HashSet<HCM_EmployeeSalary>();
            this.HCM_Final_Settlement = new HashSet<HCM_Final_Settlement>();
            this.HCM_Final_Settlement1 = new HashSet<HCM_Final_Settlement>();
            this.HCM_Interest = new HashSet<HCM_Interest>();
            this.HCM_Loan_Master = new HashSet<HCM_Loan_Master>();
            this.HCM_ProvidentFund = new HashSet<HCM_ProvidentFund>();
            this.HCM_Setup_Detail1 = new HashSet<HCM_Setup_Detail>();
            this.HCM_VehicleCategoryMapping = new HashSet<HCM_VehicleCategoryMapping>();
            this.HCM_VehicleDesignationMapping = new HashSet<HCM_VehicleDesignationMapping>();
            this.HCM_VehicleInformation = new HashSet<HCM_VehicleInformation>();
            this.HCM_VehicleInformation1 = new HashSet<HCM_VehicleInformation>();
            this.HCM_VehicleInformation2 = new HashSet<HCM_VehicleInformation>();
            this.HCM_VehicleInformation3 = new HashSet<HCM_VehicleInformation>();
            this.HCM_VehicleInformation4 = new HashSet<HCM_VehicleInformation>();
        }
    
        public int SetupDetailID { get; set; }
        public int SetupMasterID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ColumnValue { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
        public bool IsDisplay { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> FoxId { get; set; }
        public string Flex1Caption { get; set; }
        public string Flex1 { get; set; }
        public string Flex2Caption { get; set; }
        public string Flex2 { get; set; }
        public string Flex3Caption { get; set; }
        public string Flex3 { get; set; }
    
        public virtual ICollection<HCM_ArrearHistory> HCM_ArrearHistory { get; set; }
        public virtual ICollection<HCM_Atribute_Mapping> HCM_Atribute_Mapping { get; set; }
        public virtual ICollection<HCM_Company_Settings> HCM_Company_Settings { get; set; }
        public virtual ICollection<HCM_CompanyFormula> HCM_CompanyFormula { get; set; }
        public virtual ICollection<HCM_EmployeeAccountDetail> HCM_EmployeeAccountDetail { get; set; }
        public virtual ICollection<HCM_EmployeeAccountDetail> HCM_EmployeeAccountDetail1 { get; set; }
        public virtual ICollection<HCM_EmployeeSalary> HCM_EmployeeSalary { get; set; }
        public virtual ICollection<HCM_Final_Settlement> HCM_Final_Settlement { get; set; }
        public virtual ICollection<HCM_Final_Settlement> HCM_Final_Settlement1 { get; set; }
        public virtual ICollection<HCM_Interest> HCM_Interest { get; set; }
        public virtual ICollection<HCM_Loan_Master> HCM_Loan_Master { get; set; }
        public virtual ICollection<HCM_ProvidentFund> HCM_ProvidentFund { get; set; }
        public virtual ICollection<HCM_Setup_Detail> HCM_Setup_Detail1 { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail2 { get; set; }
        public virtual ICollection<HCM_VehicleCategoryMapping> HCM_VehicleCategoryMapping { get; set; }
        public virtual ICollection<HCM_VehicleDesignationMapping> HCM_VehicleDesignationMapping { get; set; }
        public virtual ICollection<HCM_VehicleInformation> HCM_VehicleInformation { get; set; }
        public virtual ICollection<HCM_VehicleInformation> HCM_VehicleInformation1 { get; set; }
        public virtual ICollection<HCM_VehicleInformation> HCM_VehicleInformation2 { get; set; }
        public virtual ICollection<HCM_VehicleInformation> HCM_VehicleInformation3 { get; set; }
        public virtual ICollection<HCM_VehicleInformation> HCM_VehicleInformation4 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
