//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_BonusTransactionDetail
    {
        public int BonusTransDetailId { get; set; }
        public Nullable<System.DateTime> BonusReleaseDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<double> AllowanceAmount { get; set; }
        public Nullable<int> PayrollLogId { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> BonusId { get; set; }
    
        public virtual HCM_Bonus HCM_Bonus { get; set; }
    }
}
