//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeTaxDetails_20210217
    {
        public int EmployeeTaxId { get; set; }
        public Nullable<int> TaxForecastId { get; set; }
        public Nullable<int> PayrollLogId { get; set; }
        public Nullable<double> CurrentMonthTax { get; set; }
        public double TaxPaid { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<bool> IsSpecialDeduction { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
    }
}
