//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_IncrementSheetHistory_IncrementLetter
    {
        public int IncrementSheetHistoryId { get; set; }
        public Nullable<int> IncrementSheetInfoId { get; set; }
        public int Year { get; set; }
        public int Inflation { get; set; }
        public int Merit { get; set; }
        public int Adjustment { get; set; }
        public int Promotion { get; set; }
        public int Total { get; set; }
        public decimal Percentage { get; set; }
        public string Rating { get; set; }
        public int Basic { get; set; }
        public int Allowances { get; set; }
        public int GrossSalary { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<long> PerformanceBonus { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string PromotionDesignation { get; set; }
        public Nullable<bool> IsPromoted { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
        public string ReDesignation { get; set; }
        public Nullable<int> Fuel_RM { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<int> CarAllowance { get; set; }
        public Nullable<int> CellAllowance { get; set; }
        public Nullable<int> HardshipAllowance { get; set; }
        public Nullable<int> DislocationAllowance { get; set; }
    }
}
