//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Settlement_Detail
    {
        public int SettlementDetailId { get; set; }
        public int Settlement_typeId { get; set; }
        public int Pay_TypeId { get; set; }
        public Nullable<int> PayrollLogId { get; set; }
        public int EmployeeId { get; set; }
        public double SettlementAmount { get; set; }
        public System.DateTime cheque_Date { get; set; }
        public int cheque_No { get; set; }
        public string Bank_Detail { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LoanMasterId { get; set; }
    
        public virtual HCM_Loan_Master HCM_Loan_Master { get; set; }
        public virtual HCM_Payroll_Log HCM_Payroll_Log { get; set; }
        public virtual HCM_Setup_Pay_type HCM_Setup_Pay_type { get; set; }
        public virtual HCM_Setup_Settlement HCM_Setup_Settlement { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
