//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Atribute_Mapping
    {
        public int AtributeMappingId { get; set; }
        public int AtributeId { get; set; }
        public int AllowanceDeductionId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual HCM_Setup_Atribute HCM_Setup_Atribute { get; set; }
    }
}
