//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_IncrementSheetInfo
    {
        public HCM_IncrementSheetInfo()
        {
            this.HCM_IncrementSheetAdditional = new HashSet<HCM_IncrementSheetAdditional>();
            this.HCM_IncrementSheetHistory = new HashSet<HCM_IncrementSheetHistory>();
        }
    
        public int IncrementSheetInfoId { get; set; }
        public int EmployeeId { get; set; }
        public int Year { get; set; }
        public long WPPF { get; set; }
        public int Holidays { get; set; }
        public int LeaveAbsent { get; set; }
        public int LWP { get; set; }
        public int TotalPresent { get; set; }
        public string RequiredHours { get; set; }
        public string WorkedHours { get; set; }
        public string ShortHours { get; set; }
        public string ExcessHours { get; set; }
        public string PP_Rating { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public long PerformanceBonus { get; set; }
    
        public virtual ICollection<HCM_IncrementSheetAdditional> HCM_IncrementSheetAdditional { get; set; }
        public virtual ICollection<HCM_IncrementSheetHistory> HCM_IncrementSheetHistory { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
