//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_IncrementSheetAdditional
    {
        public int IncrementSheetAdditionalId { get; set; }
        public int IncrementSheetInfoId { get; set; }
        public int Amount { get; set; }
        public System.DateTime IncrementDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HCM_IncrementSheetInfo HCM_IncrementSheetInfo { get; set; }
    }
}
