//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeTax
    {
        public int EmployeeTaxID { get; set; }
        public int EmployeeSalaryID { get; set; }
        public int TaxID { get; set; }
        public double TaxAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
    
        public virtual HCM_EmployeeSalary HCM_EmployeeSalary { get; set; }
        public virtual HCM_Setup_Tax HCM_Setup_Tax { get; set; }
    }
}
