//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Atribute
    {
        public HCM_Setup_Atribute()
        {
            this.HCM_Atribute_Mapping = new HashSet<HCM_Atribute_Mapping>();
            this.HCM_LoanAttributeDetail = new HashSet<HCM_LoanAttributeDetail>();
            this.HCM_Setup_Atribute1 = new HashSet<HCM_Setup_Atribute>();
        }
    
        public int AtributeId { get; set; }
        public Nullable<int> FormMasterId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string AtributeName { get; set; }
        public string CssClass { get; set; }
        public string ControlType { get; set; }
        public string TableName { get; set; }
        public string DisplayMember { get; set; }
        public string ValueMember { get; set; }
        public int SortOrder { get; set; }
        public string FillByRefernceClass { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string ParentClass { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string WhereColumnName { get; set; }
    
        public virtual ICollection<HCM_Atribute_Mapping> HCM_Atribute_Mapping { get; set; }
        public virtual HCM_FormMaster HCM_FormMaster { get; set; }
        public virtual ICollection<HCM_LoanAttributeDetail> HCM_LoanAttributeDetail { get; set; }
        public virtual ICollection<HCM_Setup_Atribute> HCM_Setup_Atribute1 { get; set; }
        public virtual HCM_Setup_Atribute HCM_Setup_Atribute2 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
