//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Definitions
    {
        public int SetupDefinitionID { get; set; }
        public int SetupMasterID { get; set; }
        public string Definition { get; set; }
        public string SetupClass { get; set; }
        public bool IsActive { get; set; }
    
        public virtual HCM_Setup_Master HCM_Setup_Master { get; set; }
    }
}
