//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Additional_Allowances
    {
        public int AdditonalAllowynceID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HCM_Setup_Allowance HCM_Setup_Allowance { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
