//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeTaxDirectDeduction
    {
        public int TaxDeductionId { get; set; }
        public int AllowanceID { get; set; }
        public int TaxSlabId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> PayrollLogId { get; set; }
        public double TaxAmount { get; set; }
        public System.DateTime DeductionMonth { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HCM_Setup_Allowance HCM_Setup_Allowance { get; set; }
        public virtual HCM_Payroll_Log HCM_Payroll_Log { get; set; }
        public virtual HCM_Setup_Tax_Slab HCM_Setup_Tax_Slab { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
