//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_IncreamentHistory
    {
        public int IncreamentId { get; set; }
        public int EmployeeId { get; set; }
        public double PrevGrossSalary { get; set; }
        public double IncreamentRate { get; set; }
        public double IncreamentedGross { get; set; }
        public Nullable<System.DateTime> IncrementProcessStartDate { get; set; }
        public Nullable<System.DateTime> IncreamentAppliedDate { get; set; }
        public int IncreamentTypeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
