//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Vehicle_Master_20210217
    {
        public int VehicleMasterId { get; set; }
        public int EmployeeId { get; set; }
        public int VehicleInformationId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> AlowanceDate { get; set; }
        public Nullable<System.DateTime> CarSettlementDate { get; set; }
        public string EngineNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string ChasisNumber { get; set; }
        public bool IsOwnerShipDeduction { get; set; }
        public bool IsUpgraded { get; set; }
        public Nullable<bool> IsCarAllowance { get; set; }
        public Nullable<double> UpgradedAmount { get; set; }
        public Nullable<double> PurchaseAmount { get; set; }
        public Nullable<double> UpgradedPurchaseAmount { get; set; }
        public Nullable<double> WrittenDownValue { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<double> InstallmentAmount { get; set; }
        public Nullable<double> CurrentMonthInstallment { get; set; }
        public Nullable<System.DateTime> CurrentMonthDeductionTillDate { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> ChangeStatusDate { get; set; }
        public Nullable<int> DifferenceVehicleInformationId { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public bool IsVehiclePayment { get; set; }
    }
}
