//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Final_Settlement
    {
        public int F_SettlementID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<double> PF_Amount { get; set; }
        public Nullable<double> Arrears { get; set; }
        public Nullable<double> Leave_Encashment { get; set; }
        public Nullable<double> Car_MarketValue { get; set; }
        public Nullable<double> Car_Total_Paid { get; set; }
        public Nullable<double> Car_Payable { get; set; }
        public Nullable<double> Other_Payable { get; set; }
        public string Other_discrip { get; set; }
        public Nullable<double> Group_InsuranceAmount { get; set; }
        public Nullable<int> Insurance_type { get; set; }
        public Nullable<System.DateTime> Salary_StopDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<System.DateTime> LastWorkingDate { get; set; }
        public Nullable<int> Notice_PeriodType { get; set; }
        public Nullable<double> Bonus_Recovery { get; set; }
        public Nullable<System.DateTime> PF_ChequeDate { get; set; }
        public string PF_CheckNumber { get; set; }
        public Nullable<bool> IsPFGranted { get; set; }
        public Nullable<System.DateTime> Final_SettlementChequeDate { get; set; }
        public string Settlement_ChequeNumber { get; set; }
        public Nullable<double> Final_Amount { get; set; }
        public Nullable<bool> IsGranted { get; set; }
        public Nullable<double> Employee_PayableAmount { get; set; }
        public Nullable<System.DateTime> Emp_PayableChequeDate { get; set; }
        public string Emp_PayableChequeNumber { get; set; }
        public Nullable<bool> IsPayablePaid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> TotalLeaves { get; set; }
        public Nullable<double> LoanBalanceAmount { get; set; }
        public Nullable<bool> IsCarTakeHome { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<double> DeductedAmount { get; set; }
    
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail1 { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
