//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Vehicle_Detail
    {
        public int VehicleDetailId { get; set; }
        public int VehicleMasterId { get; set; }
        public int PayrollLogId { get; set; }
        public double InstallmentAmount { get; set; }
        public Nullable<double> Balance { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Installment_Month { get; set; }
    
        public virtual HCM_Payroll_Log HCM_Payroll_Log { get; set; }
        public virtual HCM_Vehicle_Master HCM_Vehicle_Master { get; set; }
    }
}
