//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeSalary_IncrementLetter
    {
        public int EmployeeSalaryID { get; set; }
        public int EmployeeID { get; set; }
        public double BasicSalary { get; set; }
        public Nullable<double> NetSalary { get; set; }
        public Nullable<double> GrossSalary { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
        public bool IsIncrement { get; set; }
        public bool IsGranted { get; set; }
        public Nullable<System.DateTime> IncrementProcessStartDate { get; set; }
        public Nullable<System.DateTime> IncrementAppliedDate { get; set; }
        public Nullable<int> IncrementTypeId { get; set; }
        public Nullable<double> AdvanceTaxPercent { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
    }
}
