//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Tax_Slab
    {
        public HCM_Setup_Tax_Slab()
        {
            this.HCM_EmployeeTaxDirectDeduction = new HashSet<HCM_EmployeeTaxDirectDeduction>();
            this.HCM_EmployeeTaxForecast = new HashSet<HCM_EmployeeTaxForecast>();
        }
    
        public int TaxSlabId { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string TaxSlab { get; set; }
        public Nullable<double> SalaryRangeStart { get; set; }
        public Nullable<double> SalaryRangeEnd { get; set; }
        public Nullable<double> FixedValue { get; set; }
        public Nullable<double> TaxPercent { get; set; }
        public Nullable<double> TaxAmountLimit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> YearId { get; set; }
    
        public virtual ICollection<HCM_EmployeeTaxDirectDeduction> HCM_EmployeeTaxDirectDeduction { get; set; }
        public virtual ICollection<HCM_EmployeeTaxForecast> HCM_EmployeeTaxForecast { get; set; }
        public virtual HCM_Setup_Tax HCM_Setup_Tax { get; set; }
        public virtual HCM_Setup_Year HCM_Setup_Year { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
