//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_JV_AccountAllowanceMapping
    {
        public int AccountAllowanceMappingId { get; set; }
        public int AllowanceId { get; set; }
        public int AccountId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HCM_Jv_accounts HCM_Jv_accounts { get; set; }
        public virtual HCM_Setup_Allowance HCM_Setup_Allowance { get; set; }
    }
}
