//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Tax
    {
        public HCM_Setup_Tax()
        {
            this.HCM_EmployeeTax = new HashSet<HCM_EmployeeTax>();
            this.HCM_Setup_Tax_Slab = new HashSet<HCM_Setup_Tax_Slab>();
        }
    
        public int TaxID { get; set; }
        public string TaxName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HCM_EmployeeTax> HCM_EmployeeTax { get; set; }
        public virtual ICollection<HCM_Setup_Tax_Slab> HCM_Setup_Tax_Slab { get; set; }
    }
}
