//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_PFMaster
    {
        public HCM_PFMaster()
        {
            this.HCM_PFDetail = new HashSet<HCM_PFDetail>();
            this.HCM_PFWithdraw = new HashSet<HCM_PFWithdraw>();
        }
    
        public int PFMasterId { get; set; }
        public int EmployeeId { get; set; }
        public double EmployeeContribution { get; set; }
        public double CompanyContribution { get; set; }
        public double EmployeeBalance { get; set; }
        public double CompanyBalance { get; set; }
        public double InterestIncome { get; set; }
        public Nullable<int> InterestId { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<double> ProRataInterest { get; set; }
    
        public virtual ICollection<HCM_PFDetail> HCM_PFDetail { get; set; }
        public virtual ICollection<HCM_PFWithdraw> HCM_PFWithdraw { get; set; }
    }
}
