//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Payroll_Detail
    {
        public HCM_Payroll_Detail()
        {
            this.HCM_Salary_OverTimeHistory = new HashSet<HCM_Salary_OverTimeHistory>();
        }
    
        public int PayrollDetailId { get; set; }
        public int AllowanceId { get; set; }
        public int PayrollMasterId { get; set; }
        public Nullable<double> AllowanceAmount { get; set; }
        public Nullable<double> StandardAllowanceAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
    
        public virtual HCM_Setup_Allowance HCM_Setup_Allowance { get; set; }
        public virtual HCM_Payroll_Master HCM_Payroll_Master { get; set; }
        public virtual ICollection<HCM_Salary_OverTimeHistory> HCM_Salary_OverTimeHistory { get; set; }
    }
}
