//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Wppf_Slab
    {
        public HCM_Setup_Wppf_Slab()
        {
            this.HCM_WPPF = new HashSet<HCM_WPPF>();
        }
    
        public int WppfSlabId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> YearId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<double> SalaryRangeStart { get; set; }
        public Nullable<double> SalaryRangeEnd { get; set; }
        public Nullable<double> Unit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual HCM_Setup_Year HCM_Setup_Year { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<HCM_WPPF> HCM_WPPF { get; set; }
    }
}
