//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_PFWithdraw_20220608
    {
        public int FundWithdrawID { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime WithdrawDate { get; set; }
        public double EmployeeWithdraw { get; set; }
        public double CompanyWithdraw { get; set; }
        public double InterestIncomeWithdraw { get; set; }
        public double WithdrawAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> PFMasterId { get; set; }
    }
}
