//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_FormMaster
    {
        public HCM_FormMaster()
        {
            this.HCM_Setup_Atribute = new HashSet<HCM_Setup_Atribute>();
        }
    
        public int FormMasterId { get; set; }
        public string FormName { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<HCM_Setup_Atribute> HCM_Setup_Atribute { get; set; }
    }
}
