//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_MenuItem
    {
        public HCM_Setup_MenuItem()
        {
            this.HCM_Setup_MenuItem1 = new HashSet<HCM_Setup_MenuItem>();
        }
    
        public int Menu_Item_Code { get; set; }
        public string Menu_Item_Name { get; set; }
        public string Menu_URL { get; set; }
        public Nullable<int> Parent_Menu_Item_Code { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Displayed_In_Menu { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string User_IP { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Menu_Image { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HCM_Setup_MenuItem> HCM_Setup_MenuItem1 { get; set; }
        public virtual HCM_Setup_MenuItem HCM_Setup_MenuItem2 { get; set; }
    }
}
