//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_Allowance
    {
        public HCM_Setup_Allowance()
        {
            this.HCM_Additional_Allowances = new HashSet<HCM_Additional_Allowances>();
            this.HCM_CompanyFormula = new HashSet<HCM_CompanyFormula>();
            this.HCM_EmployeeAllowanceMapping = new HashSet<HCM_EmployeeAllowanceMapping>();
            this.HCM_EmployeeSettlement = new HashSet<HCM_EmployeeSettlement>();
            this.HCM_EmployeeTaxDirectDeduction = new HashSet<HCM_EmployeeTaxDirectDeduction>();
            this.HCM_Payroll_Detail = new HashSet<HCM_Payroll_Detail>();
            this.HCM_Setup_CategoryAllowanceMapping = new HashSet<HCM_Setup_CategoryAllowanceMapping>();
            this.HCM_Setup_Gratuity = new HashSet<HCM_Setup_Gratuity>();
            this.HCM_Setup_JV_AccountAllowanceMapping = new HashSet<HCM_Setup_JV_AccountAllowanceMapping>();
            this.HCM_Setup_Arrear = new HashSet<HCM_Setup_Arrear>();
        }
    
        public int AllowanceID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string AllowanceName { get; set; }
        public string FoxproAllowance { get; set; }
        public bool IsDeduction { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> FinanceTypeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
        public bool IsTaxableIncome { get; set; }
        public Nullable<int> SpecialTypeId { get; set; }
        public bool IsProrated { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string AccountCode { get; set; }
        public bool IsGross { get; set; }
        public bool IsOneTimeTaxable { get; set; }
        public bool OnlyForTaxForecast { get; set; }
        public Nullable<bool> IsIncludeInArrear { get; set; }
        public string PayslipHeaderName { get; set; }
        public string PayslipYTDHeaderName { get; set; }
    
        public virtual ICollection<HCM_Additional_Allowances> HCM_Additional_Allowances { get; set; }
        public virtual ICollection<HCM_CompanyFormula> HCM_CompanyFormula { get; set; }
        public virtual ICollection<HCM_EmployeeAllowanceMapping> HCM_EmployeeAllowanceMapping { get; set; }
        public virtual ICollection<HCM_EmployeeSettlement> HCM_EmployeeSettlement { get; set; }
        public virtual ICollection<HCM_EmployeeTaxDirectDeduction> HCM_EmployeeTaxDirectDeduction { get; set; }
        public virtual ICollection<HCM_Payroll_Detail> HCM_Payroll_Detail { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<HCM_Setup_CategoryAllowanceMapping> HCM_Setup_CategoryAllowanceMapping { get; set; }
        public virtual ICollection<HCM_Setup_Gratuity> HCM_Setup_Gratuity { get; set; }
        public virtual ICollection<HCM_Setup_JV_AccountAllowanceMapping> HCM_Setup_JV_AccountAllowanceMapping { get; set; }
        public virtual ICollection<HCM_Setup_Arrear> HCM_Setup_Arrear { get; set; }
    }
}
