//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeTaxForecast_20210217
    {
        public int TaxForecastId { get; set; }
        public int YearId { get; set; }
        public int EmployeeId { get; set; }
        public int TaxSlabId { get; set; }
        public double TaxableIncome { get; set; }
        public double TaxNotionalAdition { get; set; }
        public double TaxableReduction { get; set; }
        public double TotalTaxableIncome { get; set; }
        public double TaxPayable { get; set; }
        public double TaxCredit { get; set; }
        public double TotalTaxPayable { get; set; }
        public double TaxMonthlyPayable { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
    }
}
