//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Jv_accounts
    {
        public HCM_Jv_accounts()
        {
            this.HCM_Setup_JV_AccountAllowanceMapping = new HashSet<HCM_Setup_JV_AccountAllowanceMapping>();
        }
    
        public int AccountId { get; set; }
        public string AccountCode { get; set; }
        public string AccountCodeSummary { get; set; }
        public string AccountName { get; set; }
        public string AccountNameSummary { get; set; }
        public string AccountType { get; set; }
        public int SortOrder { get; set; }
        public int SortOrderSummary { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HCM_Setup_JV_AccountAllowanceMapping> HCM_Setup_JV_AccountAllowanceMapping { get; set; }
    }
}
