//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_LoanAttributeDetail
    {
        public int LoanAttributeDetailID { get; set; }
        public int LoanMasterId { get; set; }
        public int AttributeId { get; set; }
        public string AttributeValue { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual HCM_Loan_Master HCM_Loan_Master { get; set; }
        public virtual HCM_Setup_Atribute HCM_Setup_Atribute { get; set; }
    }
}
