//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_CompanyFormula
    {
        public HCM_CompanyFormula()
        {
            this.HCM_Bonus = new HashSet<HCM_Bonus>();
        }
    
        public int CompanyFormulaID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public int CompanyID { get; set; }
        public string Formula { get; set; }
        public string Deductions { get; set; }
        public string Allowances { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SetupDetailID { get; set; }
        public string FormulaElementDetailId { get; set; }
        public string ElementId { get; set; }
        public string Element { get; set; }
        public string Title { get; set; }
        public string TitleActual { get; set; }
    
        public virtual ICollection<HCM_Bonus> HCM_Bonus { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual HCM_Setup_Allowance HCM_Setup_Allowance { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
    }
}
