//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Bonus
    {
        public HCM_Bonus()
        {
            this.HCM_BonusTransactionDetail = new HashSet<HCM_BonusTransactionDetail>();
        }
    
        public int BonusId { get; set; }
        public int CompanyFormulaId { get; set; }
        public System.DateTime MaxJoining { get; set; }
        public System.DateTime BonusDate { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<bool> IsRelease { get; set; }
    
        public virtual HCM_CompanyFormula HCM_CompanyFormula { get; set; }
        public virtual ICollection<HCM_BonusTransactionDetail> HCM_BonusTransactionDetail { get; set; }
    }
}
