//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeSettlement
    {
        public int SettlementId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ResignDate { get; set; }
        public bool IsSettled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsVehicleTakeHome { get; set; }
        public Nullable<double> VehiclePurhaseAmont { get; set; }
        public Nullable<double> VehicleUpgradedAmount { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<double> ReceiveableDeductedAmount { get; set; }
        public Nullable<double> TotalVehicleAmount { get; set; }
        public Nullable<double> PFAmount { get; set; }
        public Nullable<double> LoanBalanceAmount { get; set; }
        public Nullable<double> ArrearAmount { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<int> LeavesRemaining { get; set; }
        public Nullable<double> LeaveEncashment { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public string ChequeNumber { get; set; }
    
        public virtual HCM_Setup_Allowance HCM_Setup_Allowance { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
