//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Formula_Master
    {
        public int FormulaId { get; set; }
        public string AllowanceName { get; set; }
        public string Formula { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsActive { get; set; }
    }
}
