//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Company_Settings
    {
        public HCM_Company_Settings()
        {
            this.HCM_Loan_Detail = new HashSet<HCM_Loan_Detail>();
            this.HCM_Salary_OverTimeHistory = new HashSet<HCM_Salary_OverTimeHistory>();
        }
    
        public int CompanySettingsID { get; set; }
        public int CompanyID { get; set; }
        public int SetupID { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsRelationalValue { get; set; }
    
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<HCM_Loan_Detail> HCM_Loan_Detail { get; set; }
        public virtual ICollection<HCM_Salary_OverTimeHistory> HCM_Salary_OverTimeHistory { get; set; }
    }
}
