//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_ArrearHistory
    {
        public int ArrearId { get; set; }
        public int ArrearTypeId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> SalaryMasterId { get; set; }
        public double ArrearAmount { get; set; }
        public System.DateTime ArrearDate { get; set; }
        public bool IsDispersed { get; set; }
        public System.DateTime DispersedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DespersedSalaryId { get; set; }
    
        public virtual HCM_ArrearHistory HCM_ArrearHistory1 { get; set; }
        public virtual HCM_ArrearHistory HCM_ArrearHistory2 { get; set; }
        public virtual HCM_Payroll_Master HCM_Payroll_Master { get; set; }
        public virtual HCM_Payroll_Master HCM_Payroll_Master1 { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
