//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_InterestIncome
    {
        public HCM_InterestIncome()
        {
            this.HCM_ProvidentFund = new HashSet<HCM_ProvidentFund>();
        }
    
        public int InterestIncomeId { get; set; }
        public int YearOf { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<double> PrevYearIntrestIncome { get; set; }
        public Nullable<double> CurrentPFBalance { get; set; }
        public Nullable<double> IncomeInterest_Rate { get; set; }
        public Nullable<double> InterestIncome { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<double> WithdrawAmount { get; set; }
    
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual ICollection<HCM_ProvidentFund> HCM_ProvidentFund { get; set; }
    }
}
