//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Setup_TaxLaw
    {
        public HCM_Setup_TaxLaw()
        {
            this.HCM_TaxComputation = new HashSet<HCM_TaxComputation>();
        }
    
        public int TaxLawId { get; set; }
        public string TaxLawCode { get; set; }
        public string ReportingCol { get; set; }
        public string TaxLaw { get; set; }
        public string TaxLawDescription { get; set; }
        public string Formula { get; set; }
        public string Operation { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> LawTypeId { get; set; }
        public bool IsAdvanceTax { get; set; }
        public Nullable<int> YearId { get; set; }
    
        public virtual HCM_Setup_Year HCM_Setup_Year { get; set; }
        public virtual ICollection<HCM_TaxComputation> HCM_TaxComputation { get; set; }
    }
}
