//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_ProvidentFund
    {
        public int ProvidentFundId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> SetupDetailId { get; set; }
        public double EmployeeContribution { get; set; }
        public double CompanyContribution { get; set; }
        public double EmployeeBalance { get; set; }
        public double EmployeeInterest { get; set; }
        public double CompanyBalance { get; set; }
        public double CompanyInterest { get; set; }
        public double InterestIncome { get; set; }
        public Nullable<double> TotalBalance { get; set; }
        public double InterestRate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> PayrollLogId { get; set; }
        public Nullable<int> Interest_IncomeId { get; set; }
        public Nullable<int> PFWithdrawId { get; set; }
    
        public virtual HCM_InterestIncome HCM_InterestIncome { get; set; }
        public virtual HCM_Payroll_Log HCM_Payroll_Log { get; set; }
        public virtual HCM_PFWithdraw HCM_PFWithdraw { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
