//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Loan_Detail
    {
        public int LoadDetailId { get; set; }
        public int LoanMasterId { get; set; }
        public int PayrollLogId { get; set; }
        public double InstallmentAmount { get; set; }
        public Nullable<int> InterestRateId { get; set; }
        public Nullable<double> InterestAmount { get; set; }
        public double Balance { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Payment_TypeId { get; set; }
    
        public virtual HCM_Company_Settings HCM_Company_Settings { get; set; }
        public virtual HCM_Loan_Master HCM_Loan_Master { get; set; }
        public virtual HCM_Setup_Pay_type HCM_Setup_Pay_type { get; set; }
        public virtual HCM_Payroll_Log HCM_Payroll_Log { get; set; }
    }
}
