//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_Interest
    {
        public HCM_Interest()
        {
            this.HCM_Loan_Master = new HashSet<HCM_Loan_Master>();
        }
    
        public int InterestId { get; set; }
        public int CompanyId { get; set; }
        public double InterestRate { get; set; }
        public int InterestSlabYearID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<HCM_Loan_Master> HCM_Loan_Master { get; set; }
    }
}
