//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_IncrementSheetHistory
    {
        public int IncrementSheetHistoryId { get; set; }
        public int IncrementSheetInfoId { get; set; }
        public int Year { get; set; }
        public int Inflation { get; set; }
        public int Merit { get; set; }
        public int Adjustment { get; set; }
        public int Promotion { get; set; }
        public int Total { get; set; }
        public decimal Percentage { get; set; }
        public string Rating { get; set; }
        public int Basic { get; set; }
        public int Allowances { get; set; }
        public int GrossSalary { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public string PromotionDesignation { get; set; }
    
        public virtual HCM_IncrementSheetInfo HCM_IncrementSheetInfo { get; set; }
    }
}
