//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_TaxRefund
    {
        public int RefundId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
