//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_VehicleInformation
    {
        public HCM_VehicleInformation()
        {
            this.HCM_Vehicle_Master = new HashSet<HCM_Vehicle_Master>();
            this.HCM_VehicleCategoryMapping = new HashSet<HCM_VehicleCategoryMapping>();
            this.HCM_VehicleDesignationMapping = new HashSet<HCM_VehicleDesignationMapping>();
        }
    
        public int VehicleInformationId { get; set; }
        public Nullable<int> VariantId { get; set; }
        public Nullable<int> VehicleNameId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public int FuelTypeId { get; set; }
        public int ModelYear { get; set; }
        public int HoursePower { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual HCM_Setup_Detail HCM_Setup_Detail { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail1 { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail2 { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail3 { get; set; }
        public virtual HCM_Setup_Detail HCM_Setup_Detail4 { get; set; }
        public virtual ICollection<HCM_Vehicle_Master> HCM_Vehicle_Master { get; set; }
        public virtual ICollection<HCM_VehicleCategoryMapping> HCM_VehicleCategoryMapping { get; set; }
        public virtual ICollection<HCM_VehicleDesignationMapping> HCM_VehicleDesignationMapping { get; set; }
    }
}
