//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Requisition
    {
        public HRMS_Requisition()
        {
            this.HRMS_ApplicantApplication = new HashSet<HRMS_ApplicantApplication>();
        }
    
        public int RequisitionId { get; set; }
        public string RequisitionNo { get; set; }
        public int DesignationId { get; set; }
        public int DepartmentId { get; set; }
        public int RequestedVacancy { get; set; }
        public Nullable<int> ApprovedVacancy { get; set; }
        public int LocationId { get; set; }
        public int CountryId { get; set; }
        public int JobTypeId { get; set; }
        public System.DateTime ExpectedJoiningDate { get; set; }
        public bool IsReplacementRequest { get; set; }
        public System.DateTime LastApplyDate { get; set; }
        public string Remarks { get; set; }
        public int WorkflowStepDetailId { get; set; }
        public Nullable<int> WorkflowStatusId { get; set; }
        public Nullable<int> MinDegreeRequiredId { get; set; }
        public Nullable<int> MinExperienceId { get; set; }
        public Nullable<int> JobPlacementCategoryId { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> HiringReasonId { get; set; }
        public Nullable<bool> IsBudgeted { get; set; }
        public Nullable<int> SalaryRangeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsSubmitted { get; set; }
    
        public virtual ICollection<HRMS_ApplicantApplication> HRMS_ApplicantApplication { get; set; }
        public virtual HRMS_SetupDetail HRMS_SetupDetail { get; set; }
        public virtual HRMS_SetupDetail HRMS_SetupDetail1 { get; set; }
        public virtual HRMS_SetupDetail HRMS_SetupDetail2 { get; set; }
        public virtual HRMS_SetupDetail HRMS_SetupDetail3 { get; set; }
        public virtual HRMS_Setup_EducationType HRMS_Setup_EducationType { get; set; }
        public virtual HRMS_Setup_WorkflowStatus HRMS_Setup_WorkflowStatus { get; set; }
        public virtual HRMS_Setup_WorkflowStepDetail HRMS_Setup_WorkflowStepDetail { get; set; }
        public virtual Setup_Country Setup_Country { get; set; }
        public virtual Setup_Department Setup_Department { get; set; }
        public virtual Setup_Designation Setup_Designation { get; set; }
        public virtual Setup_EmployeeType Setup_EmployeeType { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
    }
}
