//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_Applicant
    {
        public HRMS_Setup_Applicant()
        {
            this.HRMS_ApplicantApplication = new HashSet<HRMS_ApplicantApplication>();
        }
    
        public int ApplicantID { get; set; }
        public int CompanyID { get; set; }
        public string LoginId { get; set; }
        public string LoginPassword { get; set; }
        public Nullable<bool> IsBlacklisted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HRMS_ApplicantApplication> HRMS_ApplicantApplication { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
