//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_EducationType
    {
        public HRMS_Setup_EducationType()
        {
            this.HCM_Employee_Education_Detail = new HashSet<HCM_Employee_Education_Detail>();
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
        }
    
        public int educationTypeId { get; set; }
        public string educationType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserIP { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<HCM_Employee_Education_Detail> HCM_Employee_Education_Detail { get; set; }
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
    }
}
