//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_ProbationEvaluationMaster
    {
        public int ProbationEvaluationMasterID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> WorkflowTaskMasterId { get; set; }
        public Nullable<int> ReviewBy { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewerComment { get; set; }
        public Nullable<int> HODId { get; set; }
        public Nullable<System.DateTime> HODReviewDate { get; set; }
        public string HODComment { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> ReviewByHR { get; set; }
        public Nullable<System.DateTime> HRReviewDate { get; set; }
        public string HRComment { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HRMS_WorkFlowTaskMaster HRMS_WorkFlowTaskMaster { get; set; }
    }
}
