//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_EmployeeBank
    {
        public int EmployeeBankId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string AccountNumber { get; set; }
        public bool DefaultBank { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<int> PayModeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HRMS_Setup_AccountType HRMS_Setup_AccountType { get; set; }
        public virtual HRMS_Setup_Bank HRMS_Setup_Bank { get; set; }
        public virtual HRMS_Setup_PayMode HRMS_Setup_PayMode { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
    }
}
