//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_PayMode
    {
        public HRMS_Setup_PayMode()
        {
            this.HRMS_EmployeeBank = new HashSet<HRMS_EmployeeBank>();
        }
    
        public int PayModeId { get; set; }
        public string PayModePrefix { get; set; }
        public string PayMode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<HRMS_EmployeeBank> HRMS_EmployeeBank { get; set; }
    }
}
