//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_WorkflowStepDetail
    {
        public HRMS_Setup_WorkflowStepDetail()
        {
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
        }
    
        public int WorkflowStepDetailId { get; set; }
        public int WorkflowMasterId { get; set; }
        public Nullable<int> StepOrder { get; set; }
        public string StepName { get; set; }
        public int WorkflowStepActionId { get; set; }
        public Nullable<bool> IsEmailRequired { get; set; }
        public Nullable<bool> IsDecisionRequired { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsHod { get; set; }
    
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual HRMS_Setup_WorkflowMaster HRMS_Setup_WorkflowMaster { get; set; }
        public virtual HRMS_Setup_WorkflowStepAction HRMS_Setup_WorkflowStepAction { get; set; }
    }
}
