//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_SetupMaster
    {
        public HRMS_SetupMaster()
        {
            this.HRMS_Setup_WorkflowFormDetail = new HashSet<HRMS_Setup_WorkflowFormDetail>();
            this.HRMS_SetupDetail = new HashSet<HRMS_SetupDetail>();
        }
    
        public int SetupMasterId { get; set; }
        public string SetupName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HRMS_Setup_WorkflowFormDetail> HRMS_Setup_WorkflowFormDetail { get; set; }
        public virtual ICollection<HRMS_SetupDetail> HRMS_SetupDetail { get; set; }
    }
}
