//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_Bank
    {
        public HRMS_Setup_Bank()
        {
            this.HRMS_EmployeeBank = new HashSet<HRMS_EmployeeBank>();
        }
    
        public int BankId { get; set; }
        public string BankDescription { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> BankMasterId { get; set; }
    
        public virtual ICollection<HRMS_EmployeeBank> HRMS_EmployeeBank { get; set; }
        public virtual HRMS_Setup_BankMaster HRMS_Setup_BankMaster { get; set; }
    }
}
