//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_NoticePeriodType
    {
        public HRMS_Setup_NoticePeriodType()
        {
            this.Setup_Employee = new HashSet<Setup_Employee>();
        }
    
        public int NoticePeriodTypeId { get; set; }
        public string NoticePeriodType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
    }
}
