//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_WorkFlowTaskMaster
    {
        public HRMS_WorkFlowTaskMaster()
        {
            this.HRMS_ProbationEvaluationMaster = new HashSet<HRMS_ProbationEvaluationMaster>();
            this.HRMS_ResignationDetail = new HashSet<HRMS_ResignationDetail>();
        }
    
        public int WorkflowTaskMasterId { get; set; }
        public int WorkflowItemId { get; set; }
        public int WorkflowStatusId { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> WorkflowMasterId { get; set; }
    
        public virtual ICollection<HRMS_ProbationEvaluationMaster> HRMS_ProbationEvaluationMaster { get; set; }
        public virtual ICollection<HRMS_ResignationDetail> HRMS_ResignationDetail { get; set; }
        public virtual HRMS_Setup_WorkflowMaster HRMS_Setup_WorkflowMaster { get; set; }
    }
}
