//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_WorkflowFormMaster
    {
        public HRMS_Setup_WorkflowFormMaster()
        {
            this.HRMS_Setup_WorkflowFormDetail = new HashSet<HRMS_Setup_WorkflowFormDetail>();
        }
    
        public int FormMasterId { get; set; }
        public string FormName { get; set; }
        public Nullable<int> WorkflowMasterId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HRMS_Setup_WorkflowFormDetail> HRMS_Setup_WorkflowFormDetail { get; set; }
        public virtual HRMS_Setup_WorkflowMaster HRMS_Setup_WorkflowMaster { get; set; }
    }
}
