//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_CandidateInfo
    {
        public int CandidateId { get; set; }
        public int ApplicantApplicationId { get; set; }
        public int CandidateStatusId { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> OfferedSalary { get; set; }
        public Nullable<int> ApprovedSalary { get; set; }
        public Nullable<bool> IsOverBudgeted { get; set; }
        public Nullable<bool> IsNADRAVerified { get; set; }
        public Nullable<bool> IsOfferAccepted { get; set; }
        public Nullable<bool> IsTrainingRequired { get; set; }
        public Nullable<System.DateTime> TrainingStartDate { get; set; }
        public Nullable<System.DateTime> TrainingEndDate { get; set; }
        public Nullable<bool> IsTraningQualified { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual HRMS_ApplicantApplication HRMS_ApplicantApplication { get; set; }
        public virtual HRMS_SetupDetail HRMS_SetupDetail { get; set; }
        public virtual HRMS_SetupDetail HRMS_SetupDetail1 { get; set; }
    }
}
