//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_WorkflowFormDetail
    {
        public int FormDetailId { get; set; }
        public int FormMasterId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> ValueTypeId { get; set; }
        public string TableName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> ControlValueID { get; set; }
    
        public virtual HRMS_Setup_ValueType HRMS_Setup_ValueType { get; set; }
        public virtual HRMS_Setup_WorkflowFormMaster HRMS_Setup_WorkflowFormMaster { get; set; }
        public virtual HRMS_SetupMaster HRMS_SetupMaster { get; set; }
    }
}
