//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_Gender
    {
        public HRMS_Setup_Gender()
        {
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.TMS_Setup_LeaveDefinition = new HashSet<TMS_Setup_LeaveDefinition>();
        }
    
        public int GenderId { get; set; }
        public string GenderTitle { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<TMS_Setup_LeaveDefinition> TMS_Setup_LeaveDefinition { get; set; }
    }
}
