//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_BankMaster
    {
        public HRMS_Setup_BankMaster()
        {
            this.HRMS_Setup_Bank = new HashSet<HRMS_Setup_Bank>();
        }
    
        public int BankMasterId { get; set; }
        public string BankName { get; set; }
        public string BankPrefix { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<HRMS_Setup_Bank> HRMS_Setup_Bank { get; set; }
    }
}
