//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Setup_WorkflowMaster
    {
        public HRMS_Setup_WorkflowMaster()
        {
            this.HRMS_Setup_WorkflowFormMaster = new HashSet<HRMS_Setup_WorkflowFormMaster>();
            this.HRMS_Setup_WorkflowStepDetail = new HashSet<HRMS_Setup_WorkflowStepDetail>();
            this.HRMS_WorkFlowTaskMaster = new HashSet<HRMS_WorkFlowTaskMaster>();
        }
    
        public int WorkflowMasterId { get; set; }
        public string WorkflowName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HRMS_Setup_WorkflowFormMaster> HRMS_Setup_WorkflowFormMaster { get; set; }
        public virtual ICollection<HRMS_Setup_WorkflowStepDetail> HRMS_Setup_WorkflowStepDetail { get; set; }
        public virtual ICollection<HRMS_WorkFlowTaskMaster> HRMS_WorkFlowTaskMaster { get; set; }
    }
}
