//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_SetupDetail
    {
        public HRMS_SetupDetail()
        {
            this.HRMS_ApplicantApplication = new HashSet<HRMS_ApplicantApplication>();
            this.HRMS_CandidateInfo = new HashSet<HRMS_CandidateInfo>();
            this.HRMS_CandidateInfo1 = new HashSet<HRMS_CandidateInfo>();
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
            this.HRMS_Requisition1 = new HashSet<HRMS_Requisition>();
            this.HRMS_Requisition2 = new HashSet<HRMS_Requisition>();
            this.HRMS_Requisition3 = new HashSet<HRMS_Requisition>();
        }
    
        public int SetupDetailId { get; set; }
        public int SetupMasterId { get; set; }
        public string SetupDetailName { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> MinRange { get; set; }
        public Nullable<int> MaxRange { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<HRMS_ApplicantApplication> HRMS_ApplicantApplication { get; set; }
        public virtual ICollection<HRMS_CandidateInfo> HRMS_CandidateInfo { get; set; }
        public virtual ICollection<HRMS_CandidateInfo> HRMS_CandidateInfo1 { get; set; }
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition1 { get; set; }
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition2 { get; set; }
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition3 { get; set; }
        public virtual HRMS_SetupMaster HRMS_SetupMaster { get; set; }
    }
}
