//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Employee_20230110
    {
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string PreviousEmployeeCode { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> PriodEndDate { get; set; }
        public Nullable<int> InchargeId { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CNIC { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PersonalEmailAddress { get; set; }
        public string OfficeEmailAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MatrialStatusId { get; set; }
        public string EmpBirthPlace { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public Nullable<System.DateTime> CNICIssueDate { get; set; }
        public Nullable<System.DateTime> CNICExpiryDate { get; set; }
        public string NTN { get; set; }
        public string SSN { get; set; }
        public Nullable<int> NoticePeriodDays { get; set; }
        public Nullable<int> ProbitionPeriodDays { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Extension { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<bool> IsContractual { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<bool> IsMultiBankAccount { get; set; }
        public string PersonalityDetail { get; set; }
        public string PictureName { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public int CostCenterId { get; set; }
        public Nullable<bool> IsListData { get; set; }
        public Nullable<int> ListID { get; set; }
        public Nullable<int> NoOfChildren { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> CountryOfBirthId { get; set; }
        public Nullable<System.DateTime> LastworkingDate { get; set; }
        public Nullable<int> HiringTypeId { get; set; }
        public Nullable<int> TerminationTypeId { get; set; }
        public Nullable<int> NoticePeriodTypeId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> HODID { get; set; }
        public int LocationId { get; set; }
        public string OfficialMobileNumber { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> ReplacedEmployeeId { get; set; }
        public bool IsAllowInterest { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> GroupInsuranceId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> ReportingCostCenterId { get; set; }
        public Nullable<int> EmployeeSubFunctionId { get; set; }
        public Nullable<bool> AttendanceAllowanceStatus { get; set; }
        public Nullable<bool> EOBIStatus { get; set; }
        public string EOBINumber { get; set; }
        public Nullable<System.DateTime> EOBIDate { get; set; }
        public string SESANumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> SapCostCenterId { get; set; }
        public Nullable<int> TempDesgId { get; set; }
        public Nullable<int> ProvincePayrollId { get; set; }
        public Nullable<int> GroupLifeInsuranceId { get; set; }
        public Nullable<int> GroupPersonalAccidentInsuranceId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string IBANNo { get; set; }
        public bool IsAdvanceTaxDeduction { get; set; }
        public Nullable<int> CompanyCodeId { get; set; }
        public Nullable<bool> IsFinalSettlement { get; set; }
        public Nullable<System.DateTime> FinalSettlementDate { get; set; }
    }
}
