//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Province
    {
        public Setup_Province()
        {
            this.Setup_City = new HashSet<Setup_City>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_Employee1 = new HashSet<Setup_Employee>();
        }
    
        public int ProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Province { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> SocialSecurityLimit { get; set; }
        public Nullable<int> MaxAmount { get; set; }
        public Nullable<double> Contribution { get; set; }
        public Nullable<int> EOBILimit { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<Setup_City> Setup_City { get; set; }
        public virtual Setup_Country Setup_Country { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee1 { get; set; }
    }
}
