//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_AD_Location
    {
        public int ADLocationId { get; set; }
        public string ADLocationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public string LDAPAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserPrincipalDomain { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Setup_Location Setup_Location { get; set; }
    }
}
