//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Department
    {
        public Setup_Department()
        {
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentPrefix { get; set; }
        public string DepartmentName { get; set; }
        public string Description { get; set; }
        public int BusinessUnitId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> IsTSEnabled { get; set; }
        public string Email { get; set; }
        public Nullable<int> FoxId { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual TS_Setup_BusinessUnit TS_Setup_BusinessUnit { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
    }
}
