//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Application
    {
        public Setup_Application()
        {
            this.Setup_ApplicationRoleMapping = new HashSet<Setup_ApplicationRoleMapping>();
            this.Setup_MenuItem = new HashSet<Setup_MenuItem>();
            this.Setup_Role = new HashSet<Setup_Role>();
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
        }
    
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> AllUserAcsessability { get; set; }
    
        public virtual ICollection<Setup_ApplicationRoleMapping> Setup_ApplicationRoleMapping { get; set; }
        public virtual ICollection<Setup_MenuItem> Setup_MenuItem { get; set; }
        public virtual ICollection<Setup_Role> Setup_Role { get; set; }
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
    }
}
