//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Employee
    {
        public Setup_Employee()
        {
            this.HCM_AbsentFlexiLog = new HashSet<HCM_AbsentFlexiLog>();
            this.HCM_Additional_Allowances = new HashSet<HCM_Additional_Allowances>();
            this.HCM_ArrearHistory = new HashSet<HCM_ArrearHistory>();
            this.HCM_EmployeeAllowanceMapping = new HashSet<HCM_EmployeeAllowanceMapping>();
            this.HCM_EmployeeOvertimeDetail = new HashSet<HCM_EmployeeOvertimeDetail>();
            this.HCM_EmployeeSalary = new HashSet<HCM_EmployeeSalary>();
            this.HCM_EmployeeSESSI_Details = new HashSet<HCM_EmployeeSESSI_Details>();
            this.HCM_EmployeeSettlement = new HashSet<HCM_EmployeeSettlement>();
            this.HCM_EmployeeTaxDirectDeduction = new HashSet<HCM_EmployeeTaxDirectDeduction>();
            this.HCM_EmployeeTaxForecast = new HashSet<HCM_EmployeeTaxForecast>();
            this.HCM_Final_Settlement = new HashSet<HCM_Final_Settlement>();
            this.HCM_IncrementSheetInfo = new HashSet<HCM_IncrementSheetInfo>();
            this.HCM_InterestIncome = new HashSet<HCM_InterestIncome>();
            this.HCM_LeaveEncashment = new HashSet<HCM_LeaveEncashment>();
            this.HCM_Loan_Master = new HashSet<HCM_Loan_Master>();
            this.HCM_MedicalReinbursment = new HashSet<HCM_MedicalReinbursment>();
            this.HCM_Payroll_Master = new HashSet<HCM_Payroll_Master>();
            this.HCM_PFWithdraw = new HashSet<HCM_PFWithdraw>();
            this.HCM_ProvidentFund = new HashSet<HCM_ProvidentFund>();
            this.HCM_Settlement_Detail = new HashSet<HCM_Settlement_Detail>();
            this.HCM_TaxComputation = new HashSet<HCM_TaxComputation>();
            this.HCM_TaxRefund = new HashSet<HCM_TaxRefund>();
            this.HCM_Vehicle_Master = new HashSet<HCM_Vehicle_Master>();
            this.HCM_WPPF = new HashSet<HCM_WPPF>();
            this.HRMS_EmployeeBank = new HashSet<HRMS_EmployeeBank>();
            this.HRMS_ResignationDetail = new HashSet<HRMS_ResignationDetail>();
            this.Setup_Employee1 = new HashSet<Setup_Employee>();
            this.Setup_Employee11 = new HashSet<Setup_Employee>();
            this.Setup_Employee12 = new HashSet<Setup_Employee>();
            this.Setup_Employee13 = new HashSet<Setup_Employee>();
            this.Setup_EmployeeCompanyMapping = new HashSet<Setup_EmployeeCompanyMapping>();
            this.Setup_UserAccessLocation = new HashSet<Setup_UserAccessLocation>();
            this.Setup_User = new HashSet<Setup_User>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string PreviousEmployeeCode { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> PriodEndDate { get; set; }
        public Nullable<int> InchargeId { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CNIC { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PersonalEmailAddress { get; set; }
        public string OfficeEmailAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MatrialStatusId { get; set; }
        public string EmpBirthPlace { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public Nullable<System.DateTime> CNICIssueDate { get; set; }
        public Nullable<System.DateTime> CNICExpiryDate { get; set; }
        public string NTN { get; set; }
        public string SSN { get; set; }
        public Nullable<int> NoticePeriodDays { get; set; }
        public Nullable<int> ProbitionPeriodDays { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Extension { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<bool> IsContractual { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<bool> IsMultiBankAccount { get; set; }
        public string PersonalityDetail { get; set; }
        public string PictureName { get; set; }
        public Nullable<System.DateTime> ResignedDate { get; set; }
        public int CostCenterId { get; set; }
        public Nullable<bool> IsListData { get; set; }
        public Nullable<int> ListID { get; set; }
        public Nullable<int> NoOfChildren { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> CountryOfBirthId { get; set; }
        public Nullable<System.DateTime> LastworkingDate { get; set; }
        public Nullable<int> HiringTypeId { get; set; }
        public Nullable<int> TerminationTypeId { get; set; }
        public Nullable<int> NoticePeriodTypeId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> HODID { get; set; }
        public int LocationId { get; set; }
        public string OfficialMobileNumber { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> ReplacedEmployeeId { get; set; }
        public bool IsAllowInterest { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> GroupInsuranceId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> ReportingCostCenterId { get; set; }
        public Nullable<int> EmployeeSubFunctionId { get; set; }
        public Nullable<bool> AttendanceAllowanceStatus { get; set; }
        public Nullable<bool> EOBIStatus { get; set; }
        public string EOBINumber { get; set; }
        public Nullable<System.DateTime> EOBIDate { get; set; }
        public string SESANumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> SapCostCenterId { get; set; }
        public Nullable<int> TempDesgId { get; set; }
        public Nullable<int> ProvincePayrollId { get; set; }
        public Nullable<int> GroupLifeInsuranceId { get; set; }
        public Nullable<int> GroupPersonalAccidentInsuranceId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string IBANNo { get; set; }
        public bool IsAdvanceTaxDeduction { get; set; }
        public Nullable<int> CompanyCodeId { get; set; }
        public Nullable<bool> IsFinalSettlement { get; set; }
        public Nullable<System.DateTime> FinalSettlementDate { get; set; }
    
        public virtual ICollection<HCM_AbsentFlexiLog> HCM_AbsentFlexiLog { get; set; }
        public virtual ICollection<HCM_Additional_Allowances> HCM_Additional_Allowances { get; set; }
        public virtual ICollection<HCM_ArrearHistory> HCM_ArrearHistory { get; set; }
        public virtual ICollection<HCM_EmployeeAllowanceMapping> HCM_EmployeeAllowanceMapping { get; set; }
        public virtual ICollection<HCM_EmployeeOvertimeDetail> HCM_EmployeeOvertimeDetail { get; set; }
        public virtual ICollection<HCM_EmployeeSalary> HCM_EmployeeSalary { get; set; }
        public virtual ICollection<HCM_EmployeeSESSI_Details> HCM_EmployeeSESSI_Details { get; set; }
        public virtual ICollection<HCM_EmployeeSettlement> HCM_EmployeeSettlement { get; set; }
        public virtual ICollection<HCM_EmployeeTaxDirectDeduction> HCM_EmployeeTaxDirectDeduction { get; set; }
        public virtual ICollection<HCM_EmployeeTaxForecast> HCM_EmployeeTaxForecast { get; set; }
        public virtual ICollection<HCM_Final_Settlement> HCM_Final_Settlement { get; set; }
        public virtual ICollection<HCM_IncrementSheetInfo> HCM_IncrementSheetInfo { get; set; }
        public virtual ICollection<HCM_InterestIncome> HCM_InterestIncome { get; set; }
        public virtual ICollection<HCM_LeaveEncashment> HCM_LeaveEncashment { get; set; }
        public virtual ICollection<HCM_Loan_Master> HCM_Loan_Master { get; set; }
        public virtual ICollection<HCM_MedicalReinbursment> HCM_MedicalReinbursment { get; set; }
        public virtual ICollection<HCM_Payroll_Master> HCM_Payroll_Master { get; set; }
        public virtual ICollection<HCM_PFWithdraw> HCM_PFWithdraw { get; set; }
        public virtual ICollection<HCM_ProvidentFund> HCM_ProvidentFund { get; set; }
        public virtual ICollection<HCM_Settlement_Detail> HCM_Settlement_Detail { get; set; }
        public virtual ICollection<HCM_TaxComputation> HCM_TaxComputation { get; set; }
        public virtual ICollection<HCM_TaxRefund> HCM_TaxRefund { get; set; }
        public virtual ICollection<HCM_Vehicle_Master> HCM_Vehicle_Master { get; set; }
        public virtual ICollection<HCM_WPPF> HCM_WPPF { get; set; }
        public virtual ICollection<HRMS_EmployeeBank> HRMS_EmployeeBank { get; set; }
        public virtual ICollection<HRMS_ResignationDetail> HRMS_ResignationDetail { get; set; }
        public virtual HRMS_Setup_BloodGroup HRMS_Setup_BloodGroup { get; set; }
        public virtual HRMS_Setup_EmployeeSubFunction HRMS_Setup_EmployeeSubFunction { get; set; }
        public virtual HRMS_Setup_Gender HRMS_Setup_Gender { get; set; }
        public virtual HRMS_Setup_Grade HRMS_Setup_Grade { get; set; }
        public virtual HRMS_Setup_GroupInsurance HRMS_Setup_GroupInsurance { get; set; }
        public virtual HRMS_Setup_HiringType HRMS_Setup_HiringType { get; set; }
        public virtual HRMS_Setup_MartialStatus HRMS_Setup_MartialStatus { get; set; }
        public virtual HRMS_Setup_Nationality HRMS_Setup_Nationality { get; set; }
        public virtual HRMS_Setup_NoticePeriodType HRMS_Setup_NoticePeriodType { get; set; }
        public virtual HRMS_Setup_Religion HRMS_Setup_Religion { get; set; }
        public virtual HRMS_Setup_TerminationType HRMS_Setup_TerminationType { get; set; }
        public virtual Setup_City Setup_City { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_CostCenter Setup_CostCenter { get; set; }
        public virtual Setup_CostCenter Setup_CostCenter1 { get; set; }
        public virtual Setup_CostCenter Setup_CostCenter2 { get; set; }
        public virtual Setup_Country Setup_Country { get; set; }
        public virtual Setup_Country Setup_Country1 { get; set; }
        public virtual Setup_Department Setup_Department { get; set; }
        public virtual Setup_Designation Setup_Designation { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee1 { get; set; }
        public virtual Setup_Employee Setup_Employee2 { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee11 { get; set; }
        public virtual Setup_Employee Setup_Employee3 { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee12 { get; set; }
        public virtual Setup_Employee Setup_Employee4 { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee13 { get; set; }
        public virtual Setup_Employee Setup_Employee5 { get; set; }
        public virtual Setup_EmployeeType Setup_EmployeeType { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Province Setup_Province { get; set; }
        public virtual ICollection<Setup_EmployeeCompanyMapping> Setup_EmployeeCompanyMapping { get; set; }
        public virtual ICollection<Setup_UserAccessLocation> Setup_UserAccessLocation { get; set; }
        public virtual ICollection<Setup_User> Setup_User { get; set; }
        public virtual Setup_Province Setup_Province1 { get; set; }
    }
}
