//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_ValueType
    {
        public Setup_ValueType()
        {
            this.Setup_ValueTypeCompanyMapping = new HashSet<Setup_ValueTypeCompanyMapping>();
        }
    
        public int ValueTypeId { get; set; }
        public string ValueType { get; set; }
        public bool IsActiive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Setup_ValueTypeCompanyMapping> Setup_ValueTypeCompanyMapping { get; set; }
    }
}
