//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_CostCenter
    {
        public Setup_CostCenter()
        {
            this.Setup_BusinessUnitCostCenterMapping = new HashSet<Setup_BusinessUnitCostCenterMapping>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_Employee1 = new HashSet<Setup_Employee>();
            this.Setup_Employee2 = new HashSet<Setup_Employee>();
        }
    
        public int CostCenterId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CostCenterCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string CostCenterName { get; set; }
        public Nullable<int> FoxId { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<Setup_BusinessUnitCostCenterMapping> Setup_BusinessUnitCostCenterMapping { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee1 { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee2 { get; set; }
    }
}
