//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Category
    {
        public Setup_Category()
        {
            this.HCM_Setup_CategoryAllowanceMapping = new HashSet<HCM_Setup_CategoryAllowanceMapping>();
            this.HCM_Setup_RM = new HashSet<HCM_Setup_RM>();
            this.HCM_VehicleCategoryMapping = new HashSet<HCM_VehicleCategoryMapping>();
            this.Setup_Designation = new HashSet<Setup_Designation>();
            this.TMS_Setup_LeaveDefinition = new HashSet<TMS_Setup_LeaveDefinition>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> FoxId { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<HCM_Setup_CategoryAllowanceMapping> HCM_Setup_CategoryAllowanceMapping { get; set; }
        public virtual ICollection<HCM_Setup_RM> HCM_Setup_RM { get; set; }
        public virtual ICollection<HCM_VehicleCategoryMapping> HCM_VehicleCategoryMapping { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<Setup_Designation> Setup_Designation { get; set; }
        public virtual ICollection<TMS_Setup_LeaveDefinition> TMS_Setup_LeaveDefinition { get; set; }
    }
}
