//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Location
    {
        public Setup_Location()
        {
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
            this.Setup_AD_Location = new HashSet<Setup_AD_Location>();
            this.Setup_Campaign = new HashSet<Setup_Campaign>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_UserAccessLocation = new HashSet<Setup_UserAccessLocation>();
        }
    
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CityId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<bool> IsHeadOffice { get; set; }
        public string ThirdPartyMappingId { get; set; }
        public Nullable<int> FoxId { get; set; }
        public Nullable<int> SocialSecurityLimit { get; set; }
        public Nullable<int> MaxAmount { get; set; }
        public Nullable<double> Contribution { get; set; }
        public Nullable<int> EOBILimit { get; set; }
    
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual ICollection<Setup_AD_Location> Setup_AD_Location { get; set; }
        public virtual ICollection<Setup_Campaign> Setup_Campaign { get; set; }
        public virtual Setup_City Setup_City { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_UserAccessLocation> Setup_UserAccessLocation { get; set; }
    }
}
