//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_BusinessUnitCostCenterMapping
    {
        public int BuCostCenterId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual Setup_CostCenter Setup_CostCenter { get; set; }
        public virtual TS_Setup_BusinessUnit TS_Setup_BusinessUnit { get; set; }
    }
}
