//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_City
    {
        public Setup_City()
        {
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_Location = new HashSet<Setup_Location>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual Setup_Country Setup_Country { get; set; }
        public virtual Setup_Province Setup_Province { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_Location> Setup_Location { get; set; }
    }
}
