//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_User
    {
        public Setup_User()
        {
            this.Setup_ApplicationRoleMapping = new HashSet<Setup_ApplicationRoleMapping>();
            this.ThirdParty_Menu_User_Mapping = new HashSet<ThirdParty_Menu_User_Mapping>();
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
            this.UserPasswordHistories = new HashSet<UserPasswordHistory>();
        }
    
        public int User_Code { get; set; }
        public string Full_Name { get; set; }
        public string Email_Address { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string User_IP { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Login_ID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public bool IsLocked { get; set; }
        public string ForgetPassword_Token { get; set; }
        public Nullable<System.DateTime> ForgetPassword_Token_CreatedDatetime { get; set; }
    
        public virtual ICollection<Setup_ApplicationRoleMapping> Setup_ApplicationRoleMapping { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual ICollection<ThirdParty_Menu_User_Mapping> ThirdParty_Menu_User_Mapping { get; set; }
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual ICollection<UserPasswordHistory> UserPasswordHistories { get; set; }
    }
}
