//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_EmployeeType
    {
        public Setup_EmployeeType()
        {
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
        }
    
        public int EmployeeTypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
        public bool IsPermenant { get; set; }
        public Nullable<int> NapCode { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
    }
}
