//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Designation
    {
        public Setup_Designation()
        {
            this.HCM_Fuel_DesignationMapping = new HashSet<HCM_Fuel_DesignationMapping>();
            this.HCM_Setup_RM = new HashSet<HCM_Setup_RM>();
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
        }
    
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> FoxId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ThirdPartyMappingId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public Nullable<int> DesignationSortOrder { get; set; }
    
        public virtual ICollection<HCM_Fuel_DesignationMapping> HCM_Fuel_DesignationMapping { get; set; }
        public virtual ICollection<HCM_Setup_RM> HCM_Setup_RM { get; set; }
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual Setup_Category Setup_Category { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
    }
}
