//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Company
    {
        public Setup_Company()
        {
            this.HCM_Company_Settings = new HashSet<HCM_Company_Settings>();
            this.HCM_CompanyFormula = new HashSet<HCM_CompanyFormula>();
            this.HCM_Employee_Education_Detail = new HashSet<HCM_Employee_Education_Detail>();
            this.HCM_Interest = new HashSet<HCM_Interest>();
            this.HCM_MedicalReinbursment = new HashSet<HCM_MedicalReinbursment>();
            this.HCM_Setup_Allowance = new HashSet<HCM_Setup_Allowance>();
            this.HCM_Setup_Atribute = new HashSet<HCM_Setup_Atribute>();
            this.HCM_Setup_Detail = new HashSet<HCM_Setup_Detail>();
            this.HCM_Setup_FomulaType = new HashSet<HCM_Setup_FomulaType>();
            this.HCM_Setup_Gratuity = new HashSet<HCM_Setup_Gratuity>();
            this.HCM_Setup_Pay_type = new HashSet<HCM_Setup_Pay_type>();
            this.HCM_SETUP_SapCostCenter = new HashSet<HCM_SETUP_SapCostCenter>();
            this.HCM_Setup_Settlement = new HashSet<HCM_Setup_Settlement>();
            this.HCM_Setup_Tax_Slab = new HashSet<HCM_Setup_Tax_Slab>();
            this.HCM_Setup_Wppf_Slab = new HashSet<HCM_Setup_Wppf_Slab>();
            this.HCM_Setup_Year = new HashSet<HCM_Setup_Year>();
            this.HCM_WPPF = new HashSet<HCM_WPPF>();
            this.HCM_WPPF1 = new HashSet<HCM_WPPF>();
            this.HRMS_Setup_Applicant = new HashSet<HRMS_Setup_Applicant>();
            this.HRMS_Setup_ReportingCostCenter = new HashSet<HRMS_Setup_ReportingCostCenter>();
            this.Setup_Area = new HashSet<Setup_Area>();
            this.Setup_Campaign = new HashSet<Setup_Campaign>();
            this.Setup_Category = new HashSet<Setup_Category>();
            this.Setup_CostCenter = new HashSet<Setup_CostCenter>();
            this.Setup_Department = new HashSet<Setup_Department>();
            this.Setup_EmployeeType = new HashSet<Setup_EmployeeType>();
            this.TMS_Setup_LeaveDefinition = new HashSet<TMS_Setup_LeaveDefinition>();
            this.Setup_CompanyDomains = new HashSet<Setup_CompanyDomains>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_EmployeeCompanyMapping = new HashSet<Setup_EmployeeCompanyMapping>();
            this.Setup_Floor = new HashSet<Setup_Floor>();
            this.Setup_Location = new HashSet<Setup_Location>();
            this.TMS_Setup_Shift = new HashSet<TMS_Setup_Shift>();
            this.TS_Setup_BusinessUnit = new HashSet<TS_Setup_BusinessUnit>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<bool> IsBonusMapp { get; set; }
    
        public virtual ICollection<HCM_Company_Settings> HCM_Company_Settings { get; set; }
        public virtual ICollection<HCM_CompanyFormula> HCM_CompanyFormula { get; set; }
        public virtual ICollection<HCM_Employee_Education_Detail> HCM_Employee_Education_Detail { get; set; }
        public virtual ICollection<HCM_Interest> HCM_Interest { get; set; }
        public virtual ICollection<HCM_MedicalReinbursment> HCM_MedicalReinbursment { get; set; }
        public virtual ICollection<HCM_Setup_Allowance> HCM_Setup_Allowance { get; set; }
        public virtual ICollection<HCM_Setup_Atribute> HCM_Setup_Atribute { get; set; }
        public virtual ICollection<HCM_Setup_Detail> HCM_Setup_Detail { get; set; }
        public virtual ICollection<HCM_Setup_FomulaType> HCM_Setup_FomulaType { get; set; }
        public virtual ICollection<HCM_Setup_Gratuity> HCM_Setup_Gratuity { get; set; }
        public virtual ICollection<HCM_Setup_Pay_type> HCM_Setup_Pay_type { get; set; }
        public virtual ICollection<HCM_SETUP_SapCostCenter> HCM_SETUP_SapCostCenter { get; set; }
        public virtual ICollection<HCM_Setup_Settlement> HCM_Setup_Settlement { get; set; }
        public virtual ICollection<HCM_Setup_Tax_Slab> HCM_Setup_Tax_Slab { get; set; }
        public virtual ICollection<HCM_Setup_Wppf_Slab> HCM_Setup_Wppf_Slab { get; set; }
        public virtual ICollection<HCM_Setup_Year> HCM_Setup_Year { get; set; }
        public virtual ICollection<HCM_WPPF> HCM_WPPF { get; set; }
        public virtual ICollection<HCM_WPPF> HCM_WPPF1 { get; set; }
        public virtual ICollection<HRMS_Setup_Applicant> HRMS_Setup_Applicant { get; set; }
        public virtual ICollection<HRMS_Setup_ReportingCostCenter> HRMS_Setup_ReportingCostCenter { get; set; }
        public virtual ICollection<Setup_Area> Setup_Area { get; set; }
        public virtual ICollection<Setup_Campaign> Setup_Campaign { get; set; }
        public virtual ICollection<Setup_Category> Setup_Category { get; set; }
        public virtual ICollection<Setup_CostCenter> Setup_CostCenter { get; set; }
        public virtual ICollection<Setup_Department> Setup_Department { get; set; }
        public virtual ICollection<Setup_EmployeeType> Setup_EmployeeType { get; set; }
        public virtual ICollection<TMS_Setup_LeaveDefinition> TMS_Setup_LeaveDefinition { get; set; }
        public virtual Setup_Group Setup_Group { get; set; }
        public virtual ICollection<Setup_CompanyDomains> Setup_CompanyDomains { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_EmployeeCompanyMapping> Setup_EmployeeCompanyMapping { get; set; }
        public virtual ICollection<Setup_Floor> Setup_Floor { get; set; }
        public virtual ICollection<Setup_Location> Setup_Location { get; set; }
        public virtual ICollection<TMS_Setup_Shift> TMS_Setup_Shift { get; set; }
        public virtual ICollection<TS_Setup_BusinessUnit> TS_Setup_BusinessUnit { get; set; }
    }
}
