//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_RoleAccess
    {
        public int Role_Access_Code { get; set; }
        public Nullable<int> Role_Code { get; set; }
        public Nullable<int> Menu_Item_Code { get; set; }
        public Nullable<bool> Has_Access { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> User_Code { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string User_IP { get; set; }
    
        public virtual Setup_MenuItem Setup_MenuItem { get; set; }
        public virtual Setup_MenuItem Setup_MenuItem1 { get; set; }
        public virtual Setup_Role Setup_Role { get; set; }
    }
}
