//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Country
    {
        public Setup_Country()
        {
            this.HRMS_Requisition = new HashSet<HRMS_Requisition>();
            this.Setup_City = new HashSet<Setup_City>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_Employee1 = new HashSet<Setup_Employee>();
            this.Setup_Province = new HashSet<Setup_Province>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual ICollection<HRMS_Requisition> HRMS_Requisition { get; set; }
        public virtual ICollection<Setup_City> Setup_City { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee1 { get; set; }
        public virtual ICollection<Setup_Province> Setup_Province { get; set; }
    }
}
