//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_City
    {
        public string Sap_CityId { get; set; }
        public string Sap_CityName { get; set; }
        public Nullable<int> HCM_CityId { get; set; }
        public string HCM_CityName { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
        public int CityId { get; set; }
    }
}
