//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_HRMS_Setup_EducationType
    {
        public int EducationTypeId { get; set; }
        public Nullable<int> SapEducationId { get; set; }
        public string SapEducationName { get; set; }
        public Nullable<int> HCMEducationId { get; set; }
        public string HCMEducationName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Isactive { get; set; }
        public string UserIP { get; set; }
    }
}
