//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_EmployeeData
    {
        public string PayrollCompany { get; set; }
        public string UserorEmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string EmployeesDesignation { get; set; }
        public string LocationGroup { get; set; }
        public string SubLocation { get; set; }
        public string Department { get; set; }
        public string SubDepartment { get; set; }
        public string EOBINumber { get; set; }
        public string Province { get; set; }
        public string DateofBirth { get; set; }
        public string DateofJoining { get; set; }
        public string PakistanCNICorPassportInformation { get; set; }
        public string OfficialEmailInformationEmailID { get; set; }
        public string CostCenterName { get; set; }
        public string CostCenter { get; set; }
        public int EmploymentStatus { get; set; }
        public string SalaryGrade { get; set; }
        public string HRCategory { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractEndDate { get; set; }
        public string HRManager { get; set; }
        public string LineManager { get; set; }
        public string HOD { get; set; }
        public string PermanentHomeAddressHouseNumber { get; set; }
        public string StreetNameandNumber { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public double MobilePhoneInformationContactNumber { get; set; }
        public string PersonalEmailInformationEmailID { get; set; }
        public string GrossSalary { get; set; }
        public string BasicSalary { get; set; }
        public Nullable<System.DateTime> EmploymentInformationLastWorkingDate { get; set; }
        public Nullable<System.DateTime> ProbationaryPeriodEndDate { get; set; }
    }
}
