//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_EmployeeType
    {
        public int EmployeeTypeId { get; set; }
        public string SapEmployeeTypeId { get; set; }
        public string SapTypeName { get; set; }
        public Nullable<int> HCMEmployeeTypeId { get; set; }
        public string HCMTypeName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> IsPermanent { get; set; }
        public Nullable<int> NapCode { get; set; }
    }
}
