//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_Province
    {
        public int ProvinceId { get; set; }
        public string SapProvinceId { get; set; }
        public string SapProvinceName { get; set; }
        public Nullable<int> HCMProvinceId { get; set; }
        public string HCMProvinceName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> SocialSecurityLimit { get; set; }
        public Nullable<int> MaxAmount { get; set; }
        public Nullable<double> Contribution { get; set; }
        public Nullable<int> EOBILimit { get; set; }
    }
}
