//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_HRMS_Setup_Gender
    {
        public int GenderId { get; set; }
        public Nullable<int> SapGenderId { get; set; }
        public string SapGenderName { get; set; }
        public Nullable<int> HCMGenderId { get; set; }
        public string HCMGenderName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
    }
}
