//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_Designation
    {
        public int DesignationId { get; set; }
        public string SapDesignationId { get; set; }
        public string SapDesignationName { get; set; }
        public Nullable<int> HCMDesignationId { get; set; }
        public string HCMDesignationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> FoxId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
