//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_HRMS_Setup_BloodGroup
    {
        public int BloodGroupId { get; set; }
        public Nullable<int> SapBloodGroupId { get; set; }
        public string SapBloodGroupName { get; set; }
        public Nullable<int> HCMBloodGroupId { get; set; }
        public string HCMBloodGroupName { get; set; }
        public bool Isactive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
