//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_SapCostCenter
    {
        public int SapCostId { get; set; }
        public string Sap_SapCostCenterId { get; set; }
        public string Sap_SapCostCenter { get; set; }
        public Nullable<int> HCM_SapCostCenterId { get; set; }
        public string HCM_SapCostCenter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
