//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_Setup_Location
    {
        public int LocationId { get; set; }
        public string SapLocationId { get; set; }
        public string SapLocationName { get; set; }
        public Nullable<int> HCMLocationId { get; set; }
        public string HCMLocationName { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<bool> IsHeadOffice { get; set; }
    }
}
