//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_HRMS_Setup_MaritalStatus
    {
        public int MaritalStatusId { get; set; }
        public Nullable<int> SapMaritalStatusId { get; set; }
        public string SapMaritalStatusTitle { get; set; }
        public Nullable<int> HCMMaritalStatusId { get; set; }
        public string HCMMaritalStatusTitle { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    }
}
