//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpFerdeen
    {
        public Nullable<int> EMployeeID { get; set; }
        public int DesignationId { get; set; }
        public Nullable<double> Fuelpay { get; set; }
    }
}
