//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_Setup_LeaveDefinition
    {
        public int LeaveDefId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public int GenderId { get; set; }
        public bool IsActive { get; set; }
        public int AnualLeaves { get; set; }
        public int SickLeaves { get; set; }
        public int CasualLeaves { get; set; }
        public int MaternityLeaves { get; set; }
        public int DefaultLeaves { get; set; }
        public bool AnualLeavesForward { get; set; }
        public bool SickLeavesForward { get; set; }
        public bool MaternityLeavesForward { get; set; }
        public bool DefaultLeavesForward { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserIP { get; set; }
        public bool CasualLeavesFarward { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual HRMS_Setup_Gender HRMS_Setup_Gender { get; set; }
        public virtual Setup_Category Setup_Category { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
