//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_AccessFunction
    {
        public TMS_AccessFunction()
        {
            this.Setup_RoleAccessFunction = new HashSet<Setup_RoleAccessFunction>();
        }
    
        public int Access_Function_Code { get; set; }
        public string Access_Function_Name { get; set; }
    
        public virtual ICollection<Setup_RoleAccessFunction> Setup_RoleAccessFunction { get; set; }
    }
}
