//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Setup_BusinessUnit
    {
        public TS_Setup_BusinessUnit()
        {
            this.Setup_BusinessUnitCostCenterMapping = new HashSet<Setup_BusinessUnitCostCenterMapping>();
            this.Setup_Department = new HashSet<Setup_Department>();
        }
    
        public int BusinessUnitId { get; set; }
        public string BusinessUnitName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ThirdPartyMappingId { get; set; }
    
        public virtual ICollection<Setup_BusinessUnitCostCenterMapping> Setup_BusinessUnitCostCenterMapping { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual ICollection<Setup_Department> Setup_Department { get; set; }
    }
}
